name = input("What is your name? ") 
print("Hello", name)
print("Changes made by github.")
print("This line was added in the local repository.")
print("This line was added by github directly.")
print("demonstration")
